[emojis]
user_emoji =  "üôã‚Äç‚ôÇÔ∏è" # "./ui_assets/images/man.png"
chatbot_emoji = "ü§ñ" # "./ui_assets/images/robot.png"

# Define CSS styles for user and chatbot messages
[chatbot_style]
user_message_style = """
    background-color: #D5F5E3;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    display: flex;
    align-items: right;
    justify-content: flex-end;
    font-size: 18px; 
    color: black;
"""

chatbot_message_style = """
    background-color: #E5E8E8;
    padding: 10px;
    border-radius: 5px;
    margin-bottom: 10px;
    display: flex;
    align-items: left;
    font-size: 18px; 
    color: black;
    justify-content: flex-start;
"""

[theme]
primaryColor = "#E694FF"
backgroundColor = "#E6F1FF"
secondaryBackgroundColor = "#0083B8"
textColor = "#DCDCDC"
font = "sans serif"